Fix prototype of gtk_internet_radio_locator_radius
The function does not return any value in its currrent form.
Thus declaring it void fixes build failures seen in the wild such as:

[   17s] gnome-internet-radio-locator-radius.c:76:1: error: control reaches end of non-void function [-Werror=return-type]
[   17s]    76 | }